### ISSUE TITLE
Improve Thread-ability of durable sinks

### ISSUE THREAD

**Issue by rGunti** [FantasticFiasco/serilog-sinks-http#165]
**Is your feature request related to a problem? Please describe.**
When logging from multiple threads, the durable HTTP sinks like to get stuck because one thread keeps the Buffer file open and thus blocks others from writing to it / accessing it to submit data (not yet sure which exactly it is). The outcome is that the affected threads don't log to the target server while generating a few Buffer files in the process. The Debug log shows this:

```
2021-01-25T10:31:47.9066271Z Exception while emitting periodic batch from Serilog.Sinks.Http.Private.Network.HttpLogShipper: System.IO.IOException: The process cannot access the file 'G:\fakepath\Buffer.bookmark' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.Http.Private.Network.BookmarkFile..ctor(String bookmarkFileName)
   at Serilog.Sinks.Http.Private.Network.HttpLogShipper.OnTick()

2021-01-25T10:32:26.4711608Z Exception while emitting periodic batch from Serilog.Sinks.Http.Private.Network.HttpLogShipper: System.IO.IOException: The process cannot access the file 'G:\fakepath\Buffer-20210125_002.json' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
```

**Describe the solution you'd like**
Serilog's own "RollingFile" sink actually has a `shared` parameter which I personally also use since I also log to a file. In the past there was an issue in our application where we generated multiple log files at once which could be traced back to this threading issue. To fix this, I added `"shared": true` to the parameters and now it works fine.
The durable sinks should also have a similar parameter that ensures multiple threads can write to the buffer file and the submission process can correctly send the buffer content.

**Describe alternatives you've considered**
There would be the option of using the non-durable variant, which works fine from testing. But it obviously lacks the robustness that the durable variants have which should be high priority in a mission-critical application.

**Additional context**
-/-

**Comment by rGunti** [comment]
A clear case of RTFM I see... obviously right after I post the issue. I am really sorry about this.

**Comment by rGunti** [comment]
For the souls who are looking for the same solution as I have:
https://github.com/FantasticFiasco/serilog-sinks-http/wiki/Durable-file-size-rolled-HTTP-sink

The parameter is called `bufferFileShared` and defaults to `false`.

**Comment by FantasticFiasco** [comment]
Was seconds away from sending my response, you got there first 🤣 

Have a really good day!
